#!/usr/bin/env bash

set -euo pipefail

DOCKER_IMAGE="node-tc"

ROOT="$(git rev-parse --show-toplevel)"

imageBuild() {
    docker rmi $(docker images -a -q)
    docker build --tag ${DOCKER_IMAGE} --file "${ROOT}/Dockerfile" "${ROOT}"
}

testRun() {
    echo $1
    docker run --name $1 ${DOCKER_IMAGE}
}

copyReportsToJenkins() {
    sourceLocation=$1':/app/reports/.'
    destinationLocation='.'$2
    docker cp $sourceLocation $destinationLocation
}

removeContainer() {
    docker rm $1
}

removeImage() {
    docker rmi ${DOCKER_IMAGE} -f
}
"$@"